### ISSUE TITLE
Download button not working in safari

### ISSUE THREAD

**Issue by gksoriginals** [tinkerhub-org/campus-logo-generator#5]
In safari browser there is no option for saving the .png file by right clicking and saving. Adding a download button would be nice.

**Comment by gksoriginals** [comment]
Actually the svg to png button download the logo. But this is not working in Safari browser.

**Comment by gksoriginals** [comment]
@gautamkrishnar any idea why this is happening ?

**Comment by gautamkrishnar** [comment]
@GopikrishnanSasikumar from debugging, i found that the following code in script.js is not triggering in safari:
```js
    img.onload = function () {
        ctx.drawImage(img, 0, 0);
        DOMURL.revokeObjectURL(url);

        var imgURI = canvas
            .toDataURL('image/png')
            .replace('image/png', 'image/octet-stream');

        triggerDownload(imgURI);
        ctx.clearRect(0, 0, canvas.width, canvas.height);
    };
```
It is due to safari's limited blob support. We should use something like https://github.com/eligrey/FileSaver.js to implement this.

Another possible solutions are mentioned in thie SO post: https://stackoverflow.com/questions/12802109/download-blobs-locally-using-safari

**Comment by dravog7** [comment]
@gautamkrishnar  would opening the image as a new window rather than downloading work?

**Comment by gautamkrishnar** [comment]
@dravog7  That would be a good option if downloading is not at all possible in safari, i recommend you to keep consistent behavior across different browser platforms.

**Comment by ekuttan** [comment]
or let's show a browser not supported text while people login from safari.

**Comment by rohittp0** [comment]
Closing this issue as it has been resolved.
